version: "3"
services:
  database:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: prismarepro
volumes:
  pgdata:
